### ISSUE TITLE
Uncaught Error: Cannot find module './Models/video'

### ISSUE THREAD

**Issue by eduardo-moro** [Hatisoft/playyoutube-atom#9]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.40.1 x64
**Electron**: 3.1.10
**OS**: Linux Mint
**Thrown From**: [playyoutube](https://github.com/Hatisoft/playyoutube-atom) package 2.0.2

### Stack Trace

Uncaught Error: Cannot find module './Models/video'

```
At internal/modules/cjs/loader.js:604

Error: Cannot find module './Models/video'
    at Module._resolveFilename (internal/modules/cjs/loader.js:602:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:155413)
    at Module.require (/app.asar/static/index.js:61:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146745)
    at /packages/playyoutube/lib/playyoutube-atom.js:7:51)
    at /packages/playyoutube/lib/playyoutube-atom.js:137:2)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:147429)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150977)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:20:18)
    at customRequire (/usr/share/atom/resources/app/static/<embedded>:1:688157)
    at Package.requireMainModule (/usr/share/atom/resources/app/static/<embedded>:11:3304913)
    at Package.activateConfig (/usr/share/atom/resources/app/static/<embedded>:11:3294201)
    at PackageManager.packageHasSettings (/usr/share/atom/resources/app/static/<embedded>:11:930790)
    at PackageCard.hasSettings (/usr/share/atom/resources/app/static/<embedded>:14:2613731)
    at PackageCard.updateSettingsState (/usr/share/atom/resources/app/static/<embedded>:14:2604011)
    at PackageCard.updateInterfaceState (/usr/share/atom/resources/app/static/<embedded>:14:2603834)
    at /usr/share/atom/resources/app/static/<embedded>:14:2611964
    at /usr/share/atom/resources/app/static/<embedded>:14:2613982
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1209208)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1210649)
    at PackageManager.emitPackageEvent (/usr/share/atom/resources/app/static/<embedded>:11:940247)
    at /usr/share/atom/resources/app/static/<embedded>:11:937379
    at r (/usr/share/atom/resources/app/static/<embedded>:11:931909)
    at n (/usr/share/atom/resources/app/static/<embedded>:14:1128972)
    at t.bufferStream (/usr/share/atom/resources/app/static/<embedded>:14:1129126)
```

### Commands

```
 11x -6:21.8.0 core:backspace (input.hidden-input)
     -6:13 core:confirm (input.hidden-input)
     -5:50.6.0 core:backspace (input.hidden-input)
     -5:50.3.0 intentions:highlight (input.hidden-input)
     -5:50.2.0 core:save (input.hidden-input)
  4x -5:38.7.0 core:backspace (input.hidden-input)
     -5:33.7.0 autocomplete-plus:confirm (input.hidden-input)
 15x -5:32.9.0 core:select-left (input.hidden-input)
  2x -5:30.6.0 core:move-left (input.hidden-input)
     -5:29.4.0 intentions:highlight (input.hidden-input)
     -5:28.9.0 core:save (input.hidden-input)
     -5:05.6.0 intentions:highlight (input.hidden-input)
 13x -5:05.3.0 core:undo (input.hidden-input)
     -4:58.5.0 core:save (input.hidden-input)
     -0:49.7.0 intentions:highlight (input.hidden-input)
     -0:49.7.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-browser 1.5.0 
atom-search-everywhere 1.1.0 
atom-yii 0.4.1 
auto-indent 0.5.0 
busy-signal 2.0.1 
editor-background 1.2.42 
gpp 0.4.3 
gpp-compiler 3.0.7 
hyperclick 0.1.5 
intentions 1.1.5 
language-pgsql 0.2.3 
linter 2.3.1 
linter-ui-default 1.8.0 
minimap 4.29.9 
monocolor-light-blue-syntax 2.0.0 
monokai-airwave 5.0.1 
pg-dev 0.8.2 
playyoutube 2.0.2 
pt-search 0.1.2 
related 0.3.5 
show-origin 0.2.0 
status-bar-blame 2.0.3 
terminal-plus 0.14.5 
vk-terminal 3.0.1 
```

**Comment by alvarolorentedev** [comment]
@eduardo-moro, thanks for reporting this. If you can try again it should be solved. Sorry i did not noticed the issue with the cases, as i developed it in windows at that point (strange i was also using it in mac that should be case sensitive).

**Comment by alvarolorentedev** [comment]
solved as per similar issue
